project_name: kafka-console-avro-without-schema-registry

before:
  hooks:
    - go mod download

builds:
  - main: ./main.go
    binary: kafka-console-avro-without-schema-registry
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

brews:
  - tap:
      owner: kishaningithub
      name: homebrew-tap
    folder: Formula
    homepage: "https://github.com/kishaningithub/kafka-console-avro-without-schema-registry"
    description: "Tail kafka avro topic data without confluent schema registry overhead"
    license: MIT

nfpms:
  -
    id: kafka-console-avro-without-schema-registry
    package_name: kafka-console-avro-without-schema-registry
    homepage: https://github.com/kishaningithub/kafka-console-avro-without-schema-registry
    description: Tail kafka avro topic data without confluent schema registry overhead
    license: MIT
    formats:
      - apk
      - deb
      - rpm